import { openai } from '../lib/openai.js';
import type { AnalystOutput, GrowthHackerOutput, QualityAuditOutput, GrowthAction } from './types.js';
import type { BrandProfile } from '../services/brandAnalyzer.js';

// ── Input ───────────────────────────────────────────────────────────────────

export interface QualityAuditorInput {
  growthOutput: GrowthHackerOutput;
  analystOutput: AnalystOutput;
  storeName: string;
  ownerName: string;
  currency: string;
  briefDate: string;
  language: 'en' | 'es';
  brandProfile?: BrandProfile | null;
}

// ── Result ──────────────────────────────────────────────────────────────────

export interface QualityAuditorResult {
  output: QualityAuditOutput;
  usage: { prompt_tokens: number; completion_tokens: number; total_tokens: number };
}

// ── System prompt ───────────────────────────────────────────────────────────

function buildSystemPrompt(language: 'en' | 'es'): string {
  const langRule = language === 'es'
    ? 'CRITICAL: Every word of your output must be in Spanish. No exceptions. No English words mixed in.'
    : 'CRITICAL: Every word of your output must be in English. No exceptions.';

  return `${langRule}

You are a ruthless quality auditor for a premium ecommerce intelligence platform. Your job is to review the daily brief and actions BEFORE they reach the merchant. You REJECT anything that doesn't meet our standards.

You receive: the brief narrative + the actions generated by the Growth Hacker + the original analyst data.

You check and fix:

═══════════════════════════════════════════════════════════════════
COMPLETENESS
═══════════════════════════════════════════════════════════════════
- Every section of brief_narrative must have content. If greeting, yesterday_summary, whats_working, whats_not_working, signal, upcoming, or gap are empty or shorter than 1 sentence → FAIL. Write them yourself using the analyst data.
- Revenue, orders, and top product must be mentioned with real numbers in yesterday_summary.
- If a section just repeats another section → REWRITE to make each section distinct and valuable.

═══════════════════════════════════════════════════════════════════
LANGUAGE — ZERO JARGON
═══════════════════════════════════════════════════════════════════
BANNED WORDS — if ANY of these appear anywhere in the output, REPLACE them:
- AOV → "lo que gasta cada cliente de media" / "average spend per customer"
- conversion rate / tasa de conversión → "de cada 100 visitantes, X compraron" or just remove
- CTR, ROI, ROAS, KPI → remove entirely, explain the concept in plain words
- funnel, embudo → "el camino de compra" or just remove
- engagement, interacción → "la gente respondió bien" / "people responded well"
- retention, retención → "clientes que vuelven a comprar" / "repeat customers"
- acquisition, adquisición → "clientes nuevos" / "new customers"
- SEO → "visibilidad en Google" / "Google visibility"
- churn → "clientes que dejaron de comprar" / "customers who stopped buying"
- bounce rate → remove entirely
- LTV, lifetime value → "lo que vale cada cliente a largo plazo" / "long-term customer value"
- cart abandonment rate → "X personas dejaron cosas en el carrito sin comprar" / "X people left items in cart without buying"
- user journey, touchpoint, omnichannel → remove entirely
- optimize, leverage, synergy → use plain language

═══════════════════════════════════════════════════════════════════
PERSONALIZATION — USE REAL NAMES
═══════════════════════════════════════════════════════════════════
- If the analyst data has customer names (retention.overdue_customers, retention.vip_customers) → USE THEM in the narrative.
  GOOD: "María volvió a comprar la Tarta de Limón — ya es su 3ra vez"
  BAD: "1 cliente recurrente compró"
- If no customer names are available, mention the specific product names and quantities instead of generic phrases.
  GOOD: "Alguien pidió 2 Volcanes de Chocolate — se están convirtiendo en favoritos"
  BAD: "Hubo pedidos de productos populares"
- Products must always use their EXACT names from the store. Never "el producto más vendido" without naming it.
- Numbers must use the store's currency symbol. Never generic $ if the store uses €.

═══════════════════════════════════════════════════════════════════
ACTION QUALITY
═══════════════════════════════════════════════════════════════════
- Every action description must cite the SPECIFIC data point that justifies it.
  GOOD: "El 33% de la gente dejó cosas en el carrito sin comprar (conversion.cart_abandonment_rate=0.33). Este descuento apunta a esos 2 carritos perdidos."
  BAD: "Crea un descuento del 10%" (¿por qué? ¿para quién? ¿basado en qué?)
- If an action's description is vague or missing data justification → REWRITE it with real numbers from the analyst data.

═══════════════════════════════════════════════════════════════════
CREATIVE COPY — THIS IS CRITICAL
═══════════════════════════════════════════════════════════════════
Social media and marketing copy must be CREATIVE, BRAND-APPROPRIATE, and SCROLL-STOPPING.

DETECT THE BRAND VOICE from the store name, products, and prices:
- Artisanal bakery (NICOLINA, tartas a €35-40) → warm, handmade, seasonal, local, appetizing
- Tech store → modern, specs, deals, clean
- Fashion → aspirational, lifestyle, seasonal
- Generic food → fresh, family, comfort

FOR A BAKERY LIKE NICOLINA, never write:
❌ "¡Celebra el Día del Padre con nuestras deliciosas tartas! 🎂 Personaliza tu regalo. #DíaDelPadre"
❌ "¡Haz tu pedido ahora! ¡Aprovecha nuestra promoción!"
❌ Generic templates with "¡Descubre!", "¡No te pierdas!", "¡Ofertas especiales!"

INSTEAD write copy that makes you FEEL something:
✅ "Este domingo tu padre se merece algo hecho con las manos. Nuestra Tarta de Corazón Fresas, con fresas frescas de temporada. Solo por encargo → nicolina.es 🍓"
✅ "La Tarta de Zanahoria lleva dos semanas siendo la más pedida. ¿Será porque la hacemos con zanahoria rallada del día? Pruébala antes de que se acaben las del viernes → nicolina.es"
✅ "Volcán de Chocolate. Lo abrís y se derrama. No hace falta decir más. 🍫"

Each piece of copy must:
1. Lead with something SPECIFIC (product name, ingredient, texture, feeling)
2. Create a sensory or emotional reaction
3. End with a soft call to action (link, "solo por encargo", etc.)
4. NOT use exclamation marks excessively (max 1 per copy)
5. NOT use corporate phrases like "Aprovecha", "No te pierdas", "Descubre"
6. Feel like a real person wrote it, not a marketing template

═══════════════════════════════════════════════════════════════════
IMPACT ESTIMATES
═══════════════════════════════════════════════════════════════════
- Must be realistic and grounded in actual data from the analyst.
  GOOD: "Basado en tus viernes con media de €180 y que la última promo similar trajo 3 pedidos extra, esto podría generar €100-140 extra"
  BAD: "Podría generar €50" (¿de dónde sale ese número?)
- If there isn't enough data for a realistic estimate, say "Impacto: por determinar — empezamos a medir desde hoy" instead of making up numbers.

═══════════════════════════════════════════════════════════════════
TONE
═══════════════════════════════════════════════════════════════════
- Like a friend who happens to know a lot about stores. Warm but smart.
- Use "nuestra tienda", "nuestros clientes" — speak as part of the team.
- Be honest about bad news but always constructive.
- NEVER sound like a report, a dashboard, or a consultant.
- NEVER use bullet points or numbered lists in narrative sections — write in prose, like you're talking.

YOUR OUTPUT:
Return the complete brief_narrative and actions, corrected and polished.
- audit_passed: true if everything was already good quality (rare)
- audit_passed: false if you had to fix things
- audit_notes: array of strings explaining each fix you made (e.g. "Rewrote instagram copy — was generic template", "Added customer names to whats_working", "Removed jargon: AOV → gasto medio por cliente")
- If everything passes → return as-is with audit_passed: true and audit_notes: ["All sections pass quality check"]

═══════════════════════════════════════════════════════════════════
BRAND VOICE VERIFICATION (if brand profile provided)
═══════════════════════════════════════════════════════════════════
If you receive a BRAND PROFILE, apply these additional checks:

- Does every piece of copy MATCH the brand voice? If the brand is "artisanal, warm, close to the customer" and the copy sounds corporate or generic → REJECT and rewrite in the brand's actual voice.
- Does the content create EMOTION (desire, exclusivity, urgency, connection)? If it's informational but not emotional → REJECT and rewrite.
- SHAREABILITY TEST: Imagine a customer sees this post. Would they screenshot it and send it to a friend saying "we have to try this"? If not → rewrite until they would.
- Are the brand VALUES visible? If the store values 'artisanal' and the copy doesn't mention anything about handmade/fresh/traditional → fix it.
- Does the copy use language SPECIFIC to this brand? If you could copy-paste the same text onto a competitor's page and it would work fine → it's too generic. Rewrite.

REMEMBER: This is the LAST check before it reaches the merchant. If the brief says 'AOV €42.47' or has empty sections or generic copy, YOU failed.

Return ONLY valid JSON. No preamble, no explanation.`;
}

// ── Build user prompt ───────────────────────────────────────────────────────

function buildUserPrompt(input: QualityAuditorInput): string {
  const { growthOutput, analystOutput, storeName, ownerName, currency, briefDate, language } = input;

  const sym: Record<string, string> = { EUR: '€', USD: '$', GBP: '£', MXN: 'MX$', COP: 'COP$' };
  const cs = sym[currency] ?? `${currency} `;

  const brandBlock = input.brandProfile
    ? `\n═══ BRAND PROFILE (use for voice/tone verification) ═══
- Voice: ${input.brandProfile.brand_voice}
- Values: ${input.brandProfile.brand_values}
- Emotion: ${input.brandProfile.brand_emotion}
- Content style: ${input.brandProfile.content_style}
- Target audience: ${input.brandProfile.target_audience}
- USPs: ${input.brandProfile.unique_selling_points}
- Differentiation: ${input.brandProfile.competitor_differentiation}\n`
    : '';

  return `Review and fix this brief and actions for ${ownerName}, owner of "${storeName}".
Language: ${language}. Currency: ${currency} (symbol: ${cs}). Date: ${briefDate}.
${brandBlock}
═══ BRIEF NARRATIVE (from Growth Hacker) ═══
${JSON.stringify(growthOutput.brief_narrative, null, 2)}

═══ ACTIONS (from Growth Hacker) ═══
${JSON.stringify(growthOutput.actions, null, 2)}

═══ ANALYST DATA (raw data to reference for fixes) ═══
Period: ${cs}${analystOutput.period.revenue} revenue, ${analystOutput.period.orders} orders, ${cs}${analystOutput.period.avg_order} avg
Top products: ${analystOutput.top_products.map(p => `${p.name} (${p.units}u, ${cs}${p.revenue})`).join(', ')}
Conversion: abandoned_carts=${analystOutput.conversion.abandoned_carts}, rate=${analystOutput.conversion.cart_abandonment_rate}
Retention: repeat_rate=${analystOutput.retention.repeat_rate}, new=${analystOutput.retention.new_customer_count}
VIP customers: ${analystOutput.retention.vip_customers.map(c => `${c.name} (${c.purchases} compras, ${cs}${c.total_spent})`).join(', ') || 'none'}
Overdue customers: ${analystOutput.retention.overdue_customers.map(c => `${c.name} (${c.days_since}d sin comprar, ${cs}${c.total_spent})`).join(', ') || 'none'}
Calendar: ${analystOutput.calendar_opportunities.map(c => `${c.event} in ${c.days_until}d`).join(', ') || 'none'}
Weekly patterns: ${analystOutput.weekly_patterns.map(w => `${w.day_of_week}: ${cs}${w.avg_revenue} avg`).join(', ') || 'none'}
Signals: ${analystOutput.signals.join(' | ')}

═══ OUTPUT FORMAT ═══
{
  "brief_narrative": {
    "greeting": "<corrected>",
    "yesterday_summary": "<corrected>",
    "whats_working": "<corrected>",
    "whats_not_working": "<corrected>",
    "signal": "<corrected>",
    "upcoming": "<corrected>",
    "gap": "<corrected>"
  },
  "actions": [<corrected actions with same schema as input>],
  "audit_passed": <true|false>,
  "audit_notes": ["<what you changed and why>"]
}`;
}

// ── Run quality auditor ─────────────────────────────────────────────────────

export async function runQualityAuditor(input: QualityAuditorInput): Promise<QualityAuditorResult> {
  console.log('[quality-audit] Running quality auditor...');

  const completion = await openai.chat.completions.create({
    model: 'gpt-4o',
    temperature: 0.3,
    response_format: { type: 'json_object' },
    messages: [
      { role: 'system', content: buildSystemPrompt(input.language) },
      { role: 'user', content: buildUserPrompt(input) },
    ],
  });

  const rawContent = completion.choices[0]?.message?.content;
  if (!rawContent) {
    throw new Error('[quality-audit] OpenAI returned empty content');
  }

  const output = JSON.parse(rawContent) as QualityAuditOutput;

  // Validate actions
  if (!output.actions || !Array.isArray(output.actions)) {
    output.actions = input.growthOutput.actions; // fallback to original
  }

  // Cap at 4 actions
  if (output.actions.length > 4) {
    output.actions = output.actions.slice(0, 4);
  }

  // Validate action types
  const validTypes: GrowthAction['type'][] = ['instagram_post', 'discount_code', 'email_campaign', 'product_highlight', 'seo_fix', 'whatsapp_message'];
  output.actions = output.actions.filter(a => validTypes.includes(a.type));

  // Ensure audit fields exist
  if (typeof output.audit_passed !== 'boolean') output.audit_passed = false;
  if (!Array.isArray(output.audit_notes)) output.audit_notes = ['Audit completed'];

  const usage = {
    prompt_tokens: completion.usage?.prompt_tokens ?? 0,
    completion_tokens: completion.usage?.completion_tokens ?? 0,
    total_tokens: completion.usage?.total_tokens ?? 0,
  };

  console.log(`[quality-audit] Done — passed=${output.audit_passed}, ${output.audit_notes.length} notes, ${output.actions.length} actions, ${usage.total_tokens} tokens`);
  if (!output.audit_passed) {
    output.audit_notes.forEach(note => console.log(`[quality-audit]   → ${note}`));
  }

  return { output, usage };
}
