import { Link } from 'react-router-dom';

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 40 }}>
      <h2 style={{ fontSize: 18, fontWeight: 600, color: '#3A2332', marginBottom: 12, letterSpacing: '-0.01em' }}>
        {title}
      </h2>
      <div style={{ fontSize: 15, color: '#7A6B63', lineHeight: 1.8 }}>
        {children}
      </div>
    </div>
  );
}

export default function Terms() {
  return (
    <div style={{ minHeight: '100vh', background: '#F7F1EC' }}>
      {/* Nav */}
      <header style={{ borderBottom: '1px solid #E8DDD6', background: '#F7F1EC' }}>
        <div style={{ maxWidth: 800, margin: '0 auto', padding: '0 24px', height: 56, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <Link to="/" style={{ fontSize: 15, fontWeight: 600, color: '#3A2332', textDecoration: 'none', letterSpacing: '-0.01em' }}>
            sillages
          </Link>
          <Link to="/login" style={{ fontSize: 13, color: '#7A6B63', textDecoration: 'none' }}>
            Sign in →
          </Link>
        </div>
      </header>

      {/* Content */}
      <main style={{ maxWidth: 680, margin: '0 auto', padding: '64px 24px 96px' }}>
        <p style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.15em', textTransform: 'uppercase', color: '#D8B07A', marginBottom: 16 }}>
          Legal
        </p>
        <h1 style={{ fontSize: 36, fontWeight: 600, color: '#3A2332', marginBottom: 8, letterSpacing: '-0.02em', lineHeight: 1.2, fontFamily: "'DM Serif Display', serif" }}>
          Terms of Service
        </h1>
        <p style={{ fontSize: 13, color: '#A89880', marginBottom: 56 }}>Last updated: May 20, 2026</p>

        <Section title="About Sillages">
          <p style={{ marginBottom: 12 }}>
            Sillages is a Shopify app that provides daily store intelligence briefs, automated cart recovery
            emails, and welcome emails for Shopify merchants. By installing and using Sillages, you agree
            to these terms.
          </p>
          <p>
            Sillages is not financial advice, legal advice, or a guarantee of business outcomes. The briefs
            and recommendations are generated by AI and reflect patterns in your store data. You are
            responsible for how you act on them.
          </p>
        </Section>

        <Section title="Pricing and billing">
          <p style={{ marginBottom: 12 }}>
            Sillages offers the following plans:
          </p>
          <ul style={{ paddingLeft: 20, display: 'flex', flexDirection: 'column', gap: 8, marginBottom: 16 }}>
            <li><strong style={{ color: '#3A2332' }}>Starter</strong> — Free. Daily intelligence brief and basic analytics.</li>
            <li><strong style={{ color: '#3A2332' }}>Growth</strong> — $29/month. Cart recovery emails, welcome emails, brand voice customization. 14-day free trial.</li>
            <li><strong style={{ color: '#3A2332' }}>Pro</strong> — $79/month. Advanced analytics, commercial calendar, priority support. 14-day free trial.</li>
            <li><strong style={{ color: '#3A2332' }}>Scale</strong> — $199/month. Multi-store support, API access, dedicated success manager. 14-day free trial.</li>
          </ul>
          <p>
            All billing is managed through the <strong style={{ color: '#3A2332' }}>Shopify Billing API</strong>.
            We do not collect or store credit card information. Charges appear on your regular Shopify invoice.
            Prices are in USD and may be subject to change with 30 days' notice.
          </p>
        </Section>

        <Section title="What you agree to">
          <p style={{ marginBottom: 12 }}>By using Sillages, you agree to:</p>
          <ul style={{ paddingLeft: 20, display: 'flex', flexDirection: 'column', gap: 8 }}>
            <li>Provide accurate information when creating your account</li>
            <li>Keep your login credentials secure</li>
            <li>Use Sillages only for lawful purposes and in connection with a real business you own or manage</li>
            <li>Not attempt to scrape, reverse-engineer, or resell the service</li>
            <li>Not use Sillages to access stores you don't have authorization to manage</li>
          </ul>
        </Section>

        <Section title="Shopify access">
          <p style={{ marginBottom: 12 }}>
            To use Sillages, you install the app from the Shopify App Store and approve the requested
            permissions. We access your store data through the Shopify API to generate briefs and send
            emails on your behalf.
          </p>
          <p>
            You can revoke access at any time by uninstalling the app from your Shopify admin under
            Settings → Apps and sales channels.
          </p>
        </Section>

        <Section title="Emails sent on your behalf">
          <p style={{ marginBottom: 12 }}>
            Sillages sends cart recovery and welcome emails to your customers using your store name.
            All emails include an unsubscribe link. You are responsible for ensuring you have the right
            to email your customers in your jurisdiction.
          </p>
        </Section>

        <Section title="Limitation of liability">
          <p style={{ marginBottom: 12 }}>
            Sillages is provided "as is". We do our best to make it accurate and reliable, but we cannot
            guarantee that briefs will always be correct or that the service will always be available.
          </p>
          <p>
            To the fullest extent permitted by law, Sillages and its operators are not liable for any
            business decisions made based on content generated by the service, for email delivery issues,
            or for any loss of data, revenue, or profits arising from your use of Sillages.
          </p>
        </Section>

        <Section title="Cancellation">
          <p style={{ marginBottom: 12 }}>
            You can cancel at any time by uninstalling Sillages from your Shopify admin. When you
            uninstall:
          </p>
          <ul style={{ paddingLeft: 20, display: 'flex', flexDirection: 'column', gap: 8 }}>
            <li>Your Shopify Billing subscription is automatically cancelled</li>
            <li>Brief generation and email sending stops immediately</li>
            <li>All your data is permanently deleted within 30 days</li>
          </ul>
          <p style={{ marginTop: 12 }}>
            You can also contact us at{' '}
            <a href="mailto:tony@richmondpartner.com" style={{ color: '#D8B07A', textDecoration: 'none' }}>tony@richmondpartner.com</a>{' '}
            to request data deletion or account closure.
          </p>
        </Section>

        <Section title="Changes to these terms">
          <p>
            We may update these terms from time to time. We'll notify you by email at least 14 days before
            any material changes take effect. Continued use of Sillages after that date means you accept the
            updated terms.
          </p>
        </Section>

        <Section title="Contact">
          <p>
            Questions? Email us at{' '}
            <a href="mailto:tony@richmondpartner.com" style={{ color: '#D8B07A', textDecoration: 'none' }}>tony@richmondpartner.com</a>.
          </p>
        </Section>
      </main>

      {/* Footer */}
      <footer style={{ borderTop: '1px solid #E8DDD6' }}>
        <div style={{ maxWidth: 800, margin: '0 auto', padding: '24px', display: 'flex', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: 16 }}>
          <p style={{ fontSize: 12, color: '#A89880' }}>© 2026 Sillages. All rights reserved.</p>
          <div style={{ display: 'flex', gap: 24 }}>
            <Link to="/privacy" style={{ fontSize: 12, color: '#A89880', textDecoration: 'none' }}>Privacy Policy</Link>
            <Link to="/terms" style={{ fontSize: 12, color: '#A89880', textDecoration: 'none' }}>Terms of Service</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
