import { Link } from 'react-router-dom';

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 40 }}>
      <h2 style={{ fontSize: 18, fontWeight: 600, color: '#3A2332', marginBottom: 12, letterSpacing: '-0.01em' }}>
        {title}
      </h2>
      <div style={{ fontSize: 15, color: '#7A6B63', lineHeight: 1.8 }}>
        {children}
      </div>
    </div>
  );
}

export default function Terms() {
  return (
    <div style={{ minHeight: '100vh', background: '#F7F1EC' }}>
      {/* Nav */}
      <header style={{ borderBottom: '1px solid #E8DDD6', background: '#F7F1EC' }}>
        <div style={{ maxWidth: 800, margin: '0 auto', padding: '0 24px', height: 56, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <Link to="/" style={{ fontSize: 15, fontWeight: 600, color: '#3A2332', textDecoration: 'none', letterSpacing: '-0.01em' }}>
            sillages
          </Link>
          <Link to="/login" style={{ fontSize: 13, color: '#7A6B63', textDecoration: 'none' }}>
            Sign in →
          </Link>
        </div>
      </header>

      {/* Content */}
      <main style={{ maxWidth: 680, margin: '0 auto', padding: '64px 24px 96px' }}>
        <p style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.15em', textTransform: 'uppercase', color: '#D8B07A', marginBottom: 16 }}>
          Legal
        </p>
        <h1 style={{ fontSize: 36, fontWeight: 600, color: '#3A2332', marginBottom: 8, letterSpacing: '-0.02em', lineHeight: 1.2, fontFamily: "'DM Serif Display', serif" }}>
          Terms of Service
        </h1>
        <p style={{ fontSize: 13, color: '#A89880', marginBottom: 56 }}>Last updated: March 2026</p>

        <Section title="What Sillages is">
          <p style={{ marginBottom: 12 }}>
            Sillages is an intelligence tool. Every morning it analyses your Shopify store's data from the
            previous day and delivers a written brief — what happened, what it means, and what to do about it.
          </p>
          <p>
            Sillages is not financial advice, legal advice, or a guarantee of business outcomes. The briefs
            are generated by an AI and reflect patterns in your store data. You are responsible for how you
            act on them.
          </p>
        </Section>

        <Section title="Beta terms">
          <p style={{ marginBottom: 12 }}>
            Sillages is currently in beta. During the beta period, the service is free to use.
          </p>
          <p style={{ marginBottom: 12 }}>
            We may change features, pricing, or availability at any time during the beta. We'll give you at
            least 14 days' notice before any paid tier goes live or any significant feature change takes
            effect.
          </p>
          <p>
            No credit card is required during the beta. When the beta ends, you'll be given the option to
            continue on a paid plan or export your data and leave.
          </p>
        </Section>

        <Section title="What you agree to">
          <p style={{ marginBottom: 12 }}>By using Sillages, you agree to:</p>
          <ul style={{ paddingLeft: 20, display: 'flex', flexDirection: 'column', gap: 8 }}>
            <li>Provide accurate information when creating your account</li>
            <li>Keep your login credentials secure</li>
            <li>Use Sillages only for lawful purposes and in connection with a real business you own or manage</li>
            <li>Not attempt to scrape, reverse-engineer, or resell the service</li>
            <li>Not use Sillages to generate briefs for stores you don't have authorisation to access</li>
          </ul>
        </Section>

        <Section title="Shopify access">
          <p style={{ marginBottom: 12 }}>
            To use Sillages, you connect your Shopify store via OAuth. We request read-only access — we
            never place orders, modify products, or change anything in your store.
          </p>
          <p>
            You can revoke our access at any time from your Shopify admin under Apps. Revoking access will
            stop brief generation but will not delete your existing briefs.
          </p>
        </Section>

        <Section title="Limitation of liability">
          <p style={{ marginBottom: 12 }}>
            Sillages is provided "as is". We do our best to make it accurate and reliable, but we can't
            guarantee that the briefs will always be correct or that the service will always be available.
          </p>
          <p>
            To the fullest extent permitted by law, Sillages and its operators are not liable for any
            business decisions made based on content generated by the service, or for any loss of data,
            revenue, or profits arising from your use of Sillages.
          </p>
        </Section>

        <Section title="Cancellation">
          <p style={{ marginBottom: 12 }}>
            You can cancel your account at any time from the Settings page or by emailing{' '}
            <a href="mailto:tony@sillages.app" style={{ color: '#D8B07A', textDecoration: 'none' }}>tony@sillages.app</a>.
          </p>
          <p>
            When you cancel, we'll stop generating briefs and delete your data within 30 days. You can
            request an export of your data before cancellation.
          </p>
        </Section>

        <Section title="Changes to these terms">
          <p>
            We may update these terms from time to time. We'll notify you by email at least 14 days before
            any material changes take effect. Continued use of Sillages after that date means you accept the
            updated terms.
          </p>
        </Section>

        <Section title="Contact">
          <p>
            Questions? Email us at{' '}
            <a href="mailto:tony@sillages.app" style={{ color: '#D8B07A', textDecoration: 'none' }}>tony@sillages.app</a>.
          </p>
        </Section>
      </main>

      {/* Footer */}
      <footer style={{ borderTop: '1px solid #E8DDD6' }}>
        <div style={{ maxWidth: 800, margin: '0 auto', padding: '24px', display: 'flex', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: 16 }}>
          <p style={{ fontSize: 12, color: '#A89880' }}>© 2026 Sillages. All rights reserved.</p>
          <div style={{ display: 'flex', gap: 24 }}>
            <Link to="/privacy" style={{ fontSize: 12, color: '#A89880', textDecoration: 'none' }}>Privacy Policy</Link>
            <Link to="/terms" style={{ fontSize: 12, color: '#A89880', textDecoration: 'none' }}>Terms of Service</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
